### ISSUE TITLE
[BUG] [In some animations and component tab, in tailwind tab content is not present]

### ISSUE THREAD

**Issue by sujal12344** [DavidHDev/react-bits#10] opened 2024-12-30 09:31 UTC
**Bug Description**
![image](https://github.com/user-attachments/assets/1e81dd08-f948-4068-b225-61482c20522a)
![image](https://github.com/user-attachments/assets/79e1f060-88a6-4bed-ba37-c93b89a14e8d)
in this some section add for tailwind tab also

**Expected behavior**
![image](https://github.com/user-attachments/assets/46627b9a-f739-4f57-9b97-74ee1ac86bc6)

**Comment by DavidHDev** [comment] 2024-12-31 15:50
Hi, this is not a bug, some components simply don't have Tailwind, will close this.

**Closed by DavidHDev** 2024-12-31 15:50 UTC
Labels: bug
